[package]
name = "rocket-project"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
rocket = { version = "0.5.1", features = ["json"] }